[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[target.win.tasks.exe]
cmd = "target/debug/nodevisa.exe"
depends-on = ["build-tauri"]

[target.osx.tasks.cli]
cmd = "target/debug/bundle/macos/Nodevisa.app/Contents/MacOS/nodevisa"
depends-on = ["build-tauri"]

[target.osx.tasks.app]
cmd = "open target/debug/bundle/macos/Nodevisa.app"
depends-on = ["build-tauri"]

[tasks.build-tauri]
cmd = "cargo tauri build --debug"
inputs = ["src-tauri", "frontend", "service", "cli", "Cargo.lock"]
outputs = ["target/debug/nodevisa"]

[dependencies]
rust = "*"
rust-src = "*"
tauri = "*"
