[target.'cfg(target_os = "macos")']
linker = "/usr/bin/cc" # xcode-select --install

# Statically link the C runtime so the executable does not depend on the MSVC runtime DLLs.
[target.'cfg(all(target_env = "msvc", target_os = "windows"))']
rustflags = ["-C", "target-feature=+crt-static"]
